import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import sharp from 'sharp';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {commands} from '../src/catalog.mjs';
import {Bridge} from '../src/bridge.mjs';
const require=createRequire(import.meta.url),{Runtime,checkedPath}=require('../editor-plugin/runtime.cjs');
test('MCP 协议、工程绑定、参数顺序、错误和图像返回',async t=>{
 const temp=await fs.mkdtemp(path.join(os.tmpdir(),'xiangsu-mcp-test-'));
 const project=path.join(temp,'project'),docs=path.join(temp,'docs');await fs.mkdir(path.join(project,'Assets'),{recursive:true});await fs.mkdir(docs);await fs.writeFile(path.join(project,'effect.dyehpj'),'{}');await fs.writeFile(path.join(docs,'SKILL.md'),'fixture');
 const config={stateRoot:path.join(temp,'sessions'),allowedRoots:[temp],catalogPath:path.join(temp,'catalog.json'),skillsRoot:docs,resourcesRoot:docs};
 await fs.writeFile(config.catalogPath,JSON.stringify(commands));await fs.writeFile(path.join(temp,'config.json'),JSON.stringify(config));
 const calls=[];
 const png=await sharp({create:{width:8,height:12,channels:4,background:'#123456'}}).png().toBuffer();
 const runtime=new Runtime(config,{getProject:()=>({path:project}),execute:async r=>{calls.push(r);if(r.commandType==='saveScreenshot')return {base64:'aGVsbG8=',mimeType:'image/png'};if(r.commandType==='deleteAsset')return {success:false,error:'fixture failure'};return {received:r};}});runtime.start();
 const transport=new StdioClientTransport({command:process.execPath,args:[fileURLToPath(new URL('../src/server.mjs',import.meta.url))],env:{...process.env,XIANGSU_MCP_CONFIG:path.join(temp,'config.json')},stderr:'pipe'});
 const client=new Client({name:'test',version:'1.0.0'});
 t.after(async()=>{await client.close();runtime.stop();await fs.rm(temp,{recursive:true,force:true});});
 await client.connect(transport);
 const list=await client.listTools();assert.equal(new Set(list.tools.map(t=>t.name)).size,list.tools.length);assert.ok(list.tools.some(t=>t.name==='setupGameScript'));
 const ctx={projectPath:project};
 const set=await client.callTool({name:'eh_setSceneObject',arguments:{...ctx,params:{properties:[{property:'visible',value:{type:'Boolean',data:false}}],guid:'fixture'}}});assert.ok(!set.isError);
 assert.deepEqual(Object.keys(calls.at(-1).params),['guid','properties']);
 const optional=await client.callTool({name:'eh_addRenderGroup',arguments:{...ctx,params:{type:'Utility'}}});assert.ok(!optional.isError);
 assert.deepEqual(Object.keys(calls.at(-1).params),['name','type']);assert.equal(calls.at(-1).params.name,undefined);
 const backupRoot=path.join(project,'.codex/backups');
 const backupNames=await fs.readdir(backupRoot);assert.equal(backupNames.length,1);
 assert.equal(await fs.readFile(path.join(backupRoot,backupNames[0],'effect.dyehpj'),'utf8'),'{}');
 await assert.rejects(()=>fs.access(path.join(backupRoot,backupNames[0],'.agents')));
 await assert.rejects(()=>fs.access(path.join(backupRoot,backupNames[0],'.codex')));
 await assert.rejects(()=>fs.access(path.join(project,'.agents')));
 await assert.rejects(()=>fs.access(path.join(project,'Agent_cowork')));
 const bad=await client.callTool({name:'eh_setSceneObject',arguments:{...ctx,params:{guid:12,properties:[]}}});assert.equal(bad.isError,true);
 const wrong=await client.callTool({name:'eh_getScene',arguments:{projectPath:temp}});assert.equal(wrong.isError,true);
 const shot=await client.callTool({name:'eh_saveScreenshot',arguments:ctx});assert.equal(shot.content[1].type,'image');assert.equal(shot.content[1].data,'aGVsbG8=');
 const oldExecute=runtime.host.execute;
 runtime.host.execute=async r=>r.commandType==='saveScreenshot'?{base64:png.toString('base64'),mimeType:'image/png'}:oldExecute(r);
 const saved=await client.callTool({name:'eh_saveScreenshot',arguments:{...ctx,params:{path:'.codex/artifacts/test.png'}}});assert.ok(!saved.isError);
 assert.deepEqual(await fs.readFile(path.join(project,'.codex/artifacts/test.png')),png);
 assert.equal(JSON.parse(saved.content[0].text).height,12);
 const beforeInvalid=calls.length;
 const invalidTouch=await client.callTool({name:'eh_previewTouch',arguments:{...ctx,params:{x:360,y:640}}});assert.equal(invalidTouch.isError,true);assert.equal(calls.length,beforeInvalid);
 const note=await client.callTool({name:'project_write_file',arguments:{...ctx,params:{path:'.codex/notes.md',text:'测试记录'}}});assert.ok(!note.isError);
 const recording=await client.callTool({name:'eh_recordPreviewVideo',arguments:{...ctx,params:{durationSeconds:1}}});assert.ok(!recording.isError);
 assert.equal(path.dirname(calls.at(-1).params.path),path.join(project,'.codex/artifacts/recordings'));
 assert.ok((await fs.stat(path.dirname(calls.at(-1).params.path))).isDirectory());
 await assert.rejects(()=>fs.access(path.join(project,'Agent_cowork')));
 const failed=await client.callTool({name:'eh_deleteAsset',arguments:{...ctx,params:{guid:'fixture'}}});assert.equal(failed.isError,true);
 const cloud=await client.callTool({name:'awaitImageGeneration',arguments:ctx});assert.equal(cloud.isError,true);assert.match(cloud.content[0].text,/CLOUD_BACKEND/);
 const resources=await client.listResources();assert.equal(resources.resources.length,3);
 const guide=resources.resources.find(r=>r.uri==='xiangsu-doc://adapter/SKILL-ADAPTER.md');assert.ok(guide);
 assert.match(client.getInstructions(),/xiangsu-doc:\/\/adapter\/SKILL-ADAPTER.md/);
 const guideText=(await client.readResource({uri:guide.uri})).contents[0].text;
 assert.equal(guideText,await fs.readFile(new URL('../docs/SKILL-ADAPTER.md',import.meta.url),'utf8'));
 const capability=await client.callTool({name:'xiangsu_capabilities',arguments:{}});
 assert.equal(JSON.parse(capability.content[0].text).documentation.guideUri,guide.uri);
 const official=resources.resources.find(r=>r.uri.startsWith('xiangsu-doc://skills/'));
 assert.equal((await client.readResource({uri:official.uri})).contents[0].text,'fixture');
 await assert.rejects(()=>client.readResource({uri:'xiangsu-doc://adapter/..%2Fconfig.local.json'}));
 await fs.rename(docs,docs+'-unavailable');
 try{
  assert.deepEqual((await client.listResources()).resources.map(r=>r.uri),[guide.uri]);
  assert.equal((await client.readResource({uri:guide.uri})).contents[0].text,guideText);
 }finally{await fs.rename(docs+'-unavailable',docs);}
 await assert.rejects(()=>client.readResource({uri:'xiangsu-doc://skills/..%2Foutside.txt'}));
 const write=await client.callTool({name:'project_write_file',arguments:{...ctx,params:{path:'Assets/Test.ts',text:'// test'}}});assert.ok(!write.isError);
 const overwrite=await client.callTool({name:'project_write_file',arguments:{...ctx,params:{path:'Assets/Test.ts',text:'// changed'}}});assert.equal(overwrite.isError,true);
 const bridge=new Bridge(config.stateRoot);await assert.rejects(()=>bridge.call('getScene',{}, {...ctx,sessionId:'wrong'}));
 await assert.rejects(()=>runtime.execute({id:'x',sessionId:runtime.session,projectPath:project,command:'getScene',params:{},expiresAt:0}),/过期/);
 assert.throws(()=>checkedPath('../escape',project,true),/边界/);
});
test('跨工程软链接路径不能用于读写',async t=>{
 const temp=await fs.mkdtemp(path.join(os.tmpdir(),'xiangsu-path-test-'));t.after(()=>fs.rm(temp,{recursive:true,force:true}));
 await fs.mkdir(path.join(temp,'a'));await fs.mkdir(path.join(temp,'b'));await fs.symlink(path.join(temp,'b'),path.join(temp,'a/link'),'junction');
 assert.throws(()=>checkedPath('link/output.png',path.join(temp,'a'),true),/边界/);
});
